# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'user_command_panel_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(752, 322)
        self.Window = QtWidgets.QFrame(Form)
        self.Window.setGeometry(QtCore.QRect(10, 10, 731, 301))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Window.setFont(font)
        self.Window.setStyleSheet("QFrame{\n"
"    border-radius: 7px;\n"
"    background-color: #1B1D23;\n"
"}\n"
"\n"
"QLabel{\n"
"    color: white;\n"
"}\n"
"\n"
"QLineEdit{\n"
"    border-radius: 12px;\n"
"}\n"
"\n"
"QTextEdit{\n"
"    background-color: white;\n"
"    border-radius: 12px;\n"
"}")
        self.Window.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Window.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Window.setObjectName("Window")
        self.WindowFrame = QtWidgets.QFrame(self.Window)
        self.WindowFrame.setGeometry(QtCore.QRect(0, 0, 731, 31))
        self.WindowFrame.setStyleSheet("QFrame{\n"
"    border-bottom-left-radius: 0px;\n"
"    border-bottom-right-radius: 0px;\n"
"    background-color: #2C313C;\n"
"}")
        self.WindowFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.WindowFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.WindowFrame.setObjectName("WindowFrame")
        self.CloseWindowButton = QtWidgets.QPushButton(self.WindowFrame)
        self.CloseWindowButton.setGeometry(QtCore.QRect(690, 0, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.CloseWindowButton.setFont(font)
        self.CloseWindowButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.CloseWindowButton.setStyleSheet("QPushButton{\n"
"    color: white;\n"
"    border: none;\n"
"    border-top-right-radius: 7px;\n"
"    background-color: #2C313C;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #45494D;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    color: #EA2F4E;\n"
"}")
        self.CloseWindowButton.setObjectName("CloseWindowButton")
        self.MinimizeWindowButton = QtWidgets.QPushButton(self.WindowFrame)
        self.MinimizeWindowButton.setGeometry(QtCore.QRect(649, 0, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.MinimizeWindowButton.setFont(font)
        self.MinimizeWindowButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.MinimizeWindowButton.setStyleSheet("QPushButton{\n"
"    color: white;\n"
"    border: none;\n"
"    border-top-right-radius: 7px;\n"
"    background-color: #2C313C;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #45494D;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    color: #EA2F4E;\n"
"}")
        self.MinimizeWindowButton.setDefault(False)
        self.MinimizeWindowButton.setObjectName("MinimizeWindowButton")
        self.CommandNameLineEdit = QtWidgets.QLineEdit(self.Window)
        self.CommandNameLineEdit.setGeometry(QtCore.QRect(20, 50, 301, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.CommandNameLineEdit.setFont(font)
        self.CommandNameLineEdit.setInputMask("")
        self.CommandNameLineEdit.setObjectName("CommandNameLineEdit")
        self.CommandlineEdit = QtWidgets.QLineEdit(self.Window)
        self.CommandlineEdit.setGeometry(QtCore.QRect(20, 100, 301, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.CommandlineEdit.setFont(font)
        self.CommandlineEdit.setInputMask("")
        self.CommandlineEdit.setObjectName("CommandlineEdit")
        self.CommandAnsweTextEdit = QtWidgets.QTextEdit(self.Window)
        self.CommandAnsweTextEdit.setGeometry(QtCore.QRect(20, 150, 301, 81))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.CommandAnsweTextEdit.setFont(font)
        self.CommandAnsweTextEdit.setObjectName("CommandAnsweTextEdit")
        self.TextEdit = QtWidgets.QTextEdit(self.Window)
        self.TextEdit.setGeometry(QtCore.QRect(330, 50, 381, 231))
        self.TextEdit.setLineWrapMode(QtWidgets.QTextEdit.WidgetWidth)
        self.TextEdit.setReadOnly(True)
        self.TextEdit.setOverwriteMode(False)
        self.TextEdit.setAcceptRichText(True)
        self.TextEdit.setObjectName("TextEdit")
        self.UserCommandButton = QtWidgets.QPushButton(self.Window)
        self.UserCommandButton.setGeometry(QtCore.QRect(20, 240, 301, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.UserCommandButton.setFont(font)
        self.UserCommandButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.UserCommandButton.setStyleSheet("QPushButton{\n"
"    color: white;\n"
"    border-radius: 8px;\n"
"    background-color: #595F76;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #50566E;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: #434965;\n"
"}")
        self.UserCommandButton.setText("")
        self.UserCommandButton.setObjectName("UserCommandButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.CloseWindowButton.setText(_translate("Form", "X"))
        self.MinimizeWindowButton.setText(_translate("Form", "_"))
        self.CommandNameLineEdit.setPlaceholderText(_translate("Form", "Придумайте имя команде"))
        self.CommandlineEdit.setPlaceholderText(_translate("Form", "Введите команду"))
        self.CommandAnsweTextEdit.setPlaceholderText(_translate("Form", "Что должен ответить бот?"))
        self.TextEdit.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600;\">Переменные и их значения</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">1. {user} - @id{ID пользователя, который вызвал эту команду}</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">2. {db[</span><span style=\" font-size:9pt; color:#0000ff;\">Значение</span><span style=\" font-size:9pt;\">]} - у этой переменой есть 3</span><span style=\" font-size:9pt; color:#000000;\"> значений</span><span style=\" font-size:9pt;\">:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">  </span><span style=\" font-size:9pt; color:#0000ff;\">1</span><span style=\" font-size:9pt;\"> - Уровень пользователя</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">  </span><span style=\" font-size:9pt; color:#0000ff;\">2</span><span style=\" font-size:9pt;\"> - Баланс пользователя</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">  </span><span style=\" font-size:9pt; color:#0000ff;\">3</span><span style=\" font-size:9pt;\"> - Опыт пользователя</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:9pt;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600;\">Важно!</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt;\">Вызов команды всегда через &quot;!&quot;, так что в текстовом поле &quot;Введите команду&quot; не нужно водить &quot;!&quot;.</span></p></body></html>"))
