# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'user_command_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(601, 452)
        self.Window = QtWidgets.QFrame(Form)
        self.Window.setGeometry(QtCore.QRect(10, 10, 581, 431))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Window.setFont(font)
        self.Window.setStyleSheet("QFrame{\n"
"    border-radius: 7px;\n"
"    background-color: #1B1D23;\n"
"}\n"
"\n"
"QLabel{\n"
"    color: white;\n"
"}\n"
"\n"
"QLineEdit{\n"
"    border-radius: 12px;\n"
"}\n"
"\n"
"QTextEdit{\n"
"    background-color: white;\n"
"    border-radius: 12px;\n"
"}\n"
"\n"
"QScrollBar:vertical{\n"
"    border: none;\n"
"    background: #595F76;\n"
"    width: 15px;\n"
"    margin: 15px 0 15px 0;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
"QScrollBar::handle:vertical{    \n"
"    background-color: #494E61;\n"
"    min-height: 30px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color: #D5006A;\n"
"}\n"
"QScrollBar::handle:vertical:pressed{    \n"
"    background-color: #B9005C;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical{\n"
"    border: none;\n"
"    background-color: #3A3F50;\n"
"    height: 15px;\n"
"    border-top-right-radius: 7px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover{    \n"
"    background-color: #D5006A;\n"
"}\n"
"QScrollBar::sub-line:vertical:pressed{    \n"
"    background-color: #B9005C;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical{\n"
"    border: none;\n"
"    background-color: #3A3F50;\n"
"    height: 15px;\n"
"    border-bottom-right-radius: 7px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::add-line:vertical:hover{    \n"
"    background-color: #D5006A;\n"
"}\n"
"QScrollBar::add-line:vertical:pressed{    \n"
"    background-color: #B9005C;\n"
"}\n"
"\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical{\n"
"    background: none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical{\n"
"    background: none;\n"
"}")
        self.Window.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Window.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Window.setObjectName("Window")
        self.WindowFrame = QtWidgets.QFrame(self.Window)
        self.WindowFrame.setGeometry(QtCore.QRect(0, 0, 581, 31))
        self.WindowFrame.setStyleSheet("QFrame{\n"
"    border-bottom-left-radius: 0px;\n"
"    border-bottom-right-radius: 0px;\n"
"    background-color: #2C313C;\n"
"}")
        self.WindowFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.WindowFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.WindowFrame.setObjectName("WindowFrame")
        self.CloseWindowButton = QtWidgets.QPushButton(self.WindowFrame)
        self.CloseWindowButton.setGeometry(QtCore.QRect(540, 0, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.CloseWindowButton.setFont(font)
        self.CloseWindowButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.CloseWindowButton.setStyleSheet("QPushButton{\n"
"    color: white;\n"
"    border: none;\n"
"    border-top-right-radius: 7px;\n"
"    background-color: #2C313C;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #45494D;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    color: #EA2F4E;\n"
"}")
        self.CloseWindowButton.setObjectName("CloseWindowButton")
        self.MinimizeWindowButton = QtWidgets.QPushButton(self.WindowFrame)
        self.MinimizeWindowButton.setGeometry(QtCore.QRect(499, 0, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.MinimizeWindowButton.setFont(font)
        self.MinimizeWindowButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.MinimizeWindowButton.setStyleSheet("QPushButton{\n"
"    color: white;\n"
"    border: none;\n"
"    background-color: #2C313C;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #45494D;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    color: #EA2F4E;\n"
"}")
        self.MinimizeWindowButton.setDefault(False)
        self.MinimizeWindowButton.setObjectName("MinimizeWindowButton")
        self.CommandNameLineEdit = QtWidgets.QLineEdit(self.Window)
        self.CommandNameLineEdit.setGeometry(QtCore.QRect(20, 50, 361, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.CommandNameLineEdit.setFont(font)
        self.CommandNameLineEdit.setInputMask("")
        self.CommandNameLineEdit.setObjectName("CommandNameLineEdit")
        self.CommandlineEdit = QtWidgets.QLineEdit(self.Window)
        self.CommandlineEdit.setGeometry(QtCore.QRect(20, 100, 361, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.CommandlineEdit.setFont(font)
        self.CommandlineEdit.setInputMask("")
        self.CommandlineEdit.setObjectName("CommandlineEdit")
        self.CommandAnsweTextEdit = QtWidgets.QTextEdit(self.Window)
        self.CommandAnsweTextEdit.setGeometry(QtCore.QRect(20, 210, 361, 151))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.CommandAnsweTextEdit.setFont(font)
        self.CommandAnsweTextEdit.setObjectName("CommandAnsweTextEdit")
        self.UserCommandButton = QtWidgets.QPushButton(self.Window)
        self.UserCommandButton.setGeometry(QtCore.QRect(20, 370, 361, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.UserCommandButton.setFont(font)
        self.UserCommandButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.UserCommandButton.setStyleSheet("QPushButton{\n"
"    color: white;\n"
"    border-radius: 8px;\n"
"    background-color: #595F76;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #50566E;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: #434965;\n"
"}")
        self.UserCommandButton.setText("")
        self.UserCommandButton.setObjectName("UserCommandButton")
        self.Variable = QtWidgets.QFrame(self.Window)
        self.Variable.setGeometry(QtCore.QRect(390, 50, 171, 361))
        self.Variable.setStyleSheet("QFrame{\n"
"    border-radius: 12px;\n"
"    background-color: #2C313C;\n"
"}\n"
"\n"
"QPushButton{\n"
"    color: white;\n"
"    border-radius: 8px;\n"
"    background-color: #595F76;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #50566E;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: #434965;\n"
"}")
        self.Variable.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Variable.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Variable.setObjectName("Variable")
        self.AllCommandsVariableButton = QtWidgets.QPushButton(self.Variable)
        self.AllCommandsVariableButton.setGeometry(QtCore.QRect(10, 70, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.AllCommandsVariableButton.setFont(font)
        self.AllCommandsVariableButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.AllCommandsVariableButton.setObjectName("AllCommandsVariableButton")
        self.DBVariableButton = QtWidgets.QPushButton(self.Variable)
        self.DBVariableButton.setGeometry(QtCore.QRect(10, 40, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.DBVariableButton.setFont(font)
        self.DBVariableButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.DBVariableButton.setObjectName("DBVariableButton")
        self.UserVariableButton = QtWidgets.QPushButton(self.Variable)
        self.UserVariableButton.setGeometry(QtCore.QRect(10, 10, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.UserVariableButton.setFont(font)
        self.UserVariableButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.UserVariableButton.setObjectName("UserVariableButton")
        self.OtherUserVariable = QtWidgets.QPushButton(self.Variable)
        self.OtherUserVariable.setGeometry(QtCore.QRect(70, 10, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.OtherUserVariable.setFont(font)
        self.OtherUserVariable.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.OtherUserVariable.setObjectName("OtherUserVariable")
        self.OtherDBVariableButton = QtWidgets.QPushButton(self.Variable)
        self.OtherDBVariableButton.setGeometry(QtCore.QRect(60, 40, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.OtherDBVariableButton.setFont(font)
        self.OtherDBVariableButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.OtherDBVariableButton.setObjectName("OtherDBVariableButton")
        self.TakeUserIDVariableButton = QtWidgets.QPushButton(self.Variable)
        self.TakeUserIDVariableButton.setGeometry(QtCore.QRect(10, 100, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.TakeUserIDVariableButton.setFont(font)
        self.TakeUserIDVariableButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.TakeUserIDVariableButton.setObjectName("TakeUserIDVariableButton")
        self.NewUserButton = QtWidgets.QPushButton(self.Window)
        self.NewUserButton.setGeometry(QtCore.QRect(347, 147, 20, 21))
        self.NewUserButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.NewUserButton.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"}")
        self.NewUserButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Icons/iconOff.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.NewUserButton.setIcon(icon)
        self.NewUserButton.setIconSize(QtCore.QSize(16, 16))
        self.NewUserButton.setObjectName("NewUserButton")
        self.label_1 = QtWidgets.QLabel(self.Window)
        self.label_1.setGeometry(QtCore.QRect(22, 144, 324, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_1.setFont(font)
        self.label_1.setStyleSheet("")
        self.label_1.setObjectName("label_1")
        self.label_2 = QtWidgets.QLabel(self.Window)
        self.label_2.setGeometry(QtCore.QRect(22, 165, 323, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("")
        self.label_2.setObjectName("label_2")
        self.LevelUPButton = QtWidgets.QPushButton(self.Window)
        self.LevelUPButton.setGeometry(QtCore.QRect(347, 168, 20, 21))
        self.LevelUPButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.LevelUPButton.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"}")
        self.LevelUPButton.setText("")
        self.LevelUPButton.setIcon(icon)
        self.LevelUPButton.setIconSize(QtCore.QSize(16, 16))
        self.LevelUPButton.setObjectName("LevelUPButton")
        self.label_3 = QtWidgets.QLabel(self.Window)
        self.label_3.setGeometry(QtCore.QRect(22, 186, 295, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("")
        self.label_3.setObjectName("label_3")
        self.ShowCommandInCommandsListButton = QtWidgets.QPushButton(self.Window)
        self.ShowCommandInCommandsListButton.setGeometry(QtCore.QRect(318, 189, 20, 21))
        self.ShowCommandInCommandsListButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ShowCommandInCommandsListButton.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"}")
        self.ShowCommandInCommandsListButton.setText("")
        self.ShowCommandInCommandsListButton.setIcon(icon)
        self.ShowCommandInCommandsListButton.setIconSize(QtCore.QSize(16, 16))
        self.ShowCommandInCommandsListButton.setObjectName("ShowCommandInCommandsListButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.CloseWindowButton.setText(_translate("Form", "X"))
        self.MinimizeWindowButton.setText(_translate("Form", "_"))
        self.CommandNameLineEdit.setPlaceholderText(_translate("Form", "Придумайте имя команде"))
        self.CommandlineEdit.setPlaceholderText(_translate("Form", "Введите команду"))
        self.CommandAnsweTextEdit.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.CommandAnsweTextEdit.setPlaceholderText(_translate("Form", "Что должен ответить бот?"))
        self.AllCommandsVariableButton.setText(_translate("Form", "{all_commands}"))
        self.DBVariableButton.setText(_translate("Form", "{db}"))
        self.UserVariableButton.setText(_translate("Form", "{user}"))
        self.OtherUserVariable.setText(_translate("Form", "{other_user}"))
        self.OtherDBVariableButton.setText(_translate("Form", "{other_db}"))
        self.TakeUserIDVariableButton.setText(_translate("Form", "{take_user_id}"))
        self.label_1.setText(_translate("Form", "Каждому новому пользователю:"))
        self.label_2.setText(_translate("Form", "При достижении нового уровня:"))
        self.label_3.setText(_translate("Form", "Показывать в списке команд:"))
