# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'db_variable_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(342, 241)
        self.Window = QtWidgets.QFrame(Form)
        self.Window.setGeometry(QtCore.QRect(10, 10, 321, 221))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Window.setFont(font)
        self.Window.setStyleSheet("QFrame{\n"
"    border-radius: 7px;\n"
"    background-color: #1B1D23;\n"
"}\n"
"\n"
"QLabel{\n"
"    color: white;\n"
"}\n"
"\n"
"QLineEdit{\n"
"    border-radius: 12px;\n"
"}\n"
"\n"
"QTextEdit{\n"
"    background-color: white;\n"
"    border-radius: 12px;\n"
"}")
        self.Window.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Window.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Window.setObjectName("Window")
        self.WindowFrame = QtWidgets.QFrame(self.Window)
        self.WindowFrame.setGeometry(QtCore.QRect(0, 0, 321, 31))
        self.WindowFrame.setStyleSheet("QFrame{\n"
"    border-bottom-left-radius: 0px;\n"
"    border-bottom-right-radius: 0px;\n"
"    background-color: #2C313C;\n"
"}")
        self.WindowFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.WindowFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.WindowFrame.setObjectName("WindowFrame")
        self.CloseWindowButton = QtWidgets.QPushButton(self.WindowFrame)
        self.CloseWindowButton.setGeometry(QtCore.QRect(280, 0, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.CloseWindowButton.setFont(font)
        self.CloseWindowButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.CloseWindowButton.setStyleSheet("QPushButton{\n"
"    color: white;\n"
"    border: none;\n"
"    border-top-right-radius: 7px;\n"
"    background-color: #2C313C;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #45494D;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    color: #EA2F4E;\n"
"}")
        self.CloseWindowButton.setObjectName("CloseWindowButton")
        self.MinimizeWindowButton = QtWidgets.QPushButton(self.WindowFrame)
        self.MinimizeWindowButton.setGeometry(QtCore.QRect(239, 0, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.MinimizeWindowButton.setFont(font)
        self.MinimizeWindowButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.MinimizeWindowButton.setStyleSheet("QPushButton{\n"
"    color: white;\n"
"    border: none;\n"
"    background-color: #2C313C;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #45494D;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    color: #EA2F4E;\n"
"}")
        self.MinimizeWindowButton.setDefault(False)
        self.MinimizeWindowButton.setObjectName("MinimizeWindowButton")
        self.SelectDBVariableButton = QtWidgets.QPushButton(self.Window)
        self.SelectDBVariableButton.setGeometry(QtCore.QRect(60, 160, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.SelectDBVariableButton.setFont(font)
        self.SelectDBVariableButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.SelectDBVariableButton.setStyleSheet("QPushButton{\n"
"    color: white;\n"
"    border-radius: 8px;\n"
"    background-color: #595F76;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #50566E;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: #434965;\n"
"}")
        self.SelectDBVariableButton.setObjectName("SelectDBVariableButton")
        self.label = QtWidgets.QLabel(self.Window)
        self.label.setGeometry(QtCore.QRect(20, 40, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.Window)
        self.label_2.setGeometry(QtCore.QRect(20, 70, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.Window)
        self.label_3.setGeometry(QtCore.QRect(20, 90, 174, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.Window)
        self.label_4.setGeometry(QtCore.QRect(20, 110, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.Window)
        self.label_5.setGeometry(QtCore.QRect(20, 130, 154, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.UserLevelButton = QtWidgets.QPushButton(self.Window)
        self.UserLevelButton.setGeometry(QtCore.QRect(204, 73, 21, 21))
        self.UserLevelButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.UserLevelButton.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"}")
        self.UserLevelButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../Icons/Off.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.UserLevelButton.setIcon(icon)
        self.UserLevelButton.setIconSize(QtCore.QSize(16, 16))
        self.UserLevelButton.setObjectName("UserLevelButton")
        self.UserBalanceButton = QtWidgets.QPushButton(self.Window)
        self.UserBalanceButton.setGeometry(QtCore.QRect(194, 93, 20, 21))
        self.UserBalanceButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.UserBalanceButton.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"}")
        self.UserBalanceButton.setText("")
        self.UserBalanceButton.setIcon(icon)
        self.UserBalanceButton.setIconSize(QtCore.QSize(16, 16))
        self.UserBalanceButton.setObjectName("UserBalanceButton")
        self.UserExperienceButton = QtWidgets.QPushButton(self.Window)
        self.UserExperienceButton.setGeometry(QtCore.QRect(183, 113, 20, 21))
        self.UserExperienceButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.UserExperienceButton.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"}")
        self.UserExperienceButton.setText("")
        self.UserExperienceButton.setIcon(icon)
        self.UserExperienceButton.setIconSize(QtCore.QSize(16, 16))
        self.UserExperienceButton.setObjectName("UserExperienceButton")
        self.UserRankButton = QtWidgets.QPushButton(self.Window)
        self.UserRankButton.setGeometry(QtCore.QRect(174, 133, 20, 21))
        self.UserRankButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.UserRankButton.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"}")
        self.UserRankButton.setText("")
        self.UserRankButton.setIcon(icon)
        self.UserRankButton.setIconSize(QtCore.QSize(16, 16))
        self.UserRankButton.setObjectName("UserRankButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.CloseWindowButton.setText(_translate("Form", "X"))
        self.MinimizeWindowButton.setText(_translate("Form", "_"))
        self.SelectDBVariableButton.setText(_translate("Form", "Выбрать"))
        self.label.setText(_translate("Form", "ВЫБИРИТЕ ЗНАЧЕНИЕ"))
        self.label_2.setText(_translate("Form", "Уровень пользователя:"))
        self.label_3.setText(_translate("Form", "Баланс пользователя:"))
        self.label_4.setText(_translate("Form", "Опыт пользователя:"))
        self.label_5.setText(_translate("Form", "Ранг пользователя:"))
