# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings_panel.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(761, 181)
        self.Window = QtWidgets.QFrame(Form)
        self.Window.setGeometry(QtCore.QRect(10, 10, 741, 161))
        self.Window.setStyleSheet("QFrame{\n"
"    border-radius: 7px;\n"
"    background-color: #1B1D23;\n"
"}")
        self.Window.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Window.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Window.setObjectName("Window")
        self.WindowFrame = QtWidgets.QFrame(self.Window)
        self.WindowFrame.setGeometry(QtCore.QRect(0, 0, 741, 31))
        self.WindowFrame.setStyleSheet("QFrame{\n"
"    border-bottom-left-radius: 0px;\n"
"    border-bottom-right-radius: 0px;\n"
"    background-color: #2C313C;\n"
"}")
        self.WindowFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.WindowFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.WindowFrame.setObjectName("WindowFrame")
        self.CloseWindowButton = QtWidgets.QPushButton(self.WindowFrame)
        self.CloseWindowButton.setGeometry(QtCore.QRect(701, 0, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.CloseWindowButton.setFont(font)
        self.CloseWindowButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.CloseWindowButton.setStyleSheet("QPushButton{\n"
"    color: white;\n"
"    border: none;\n"
"    border-top-right-radius: 7px;\n"
"    background-color: #2C313C;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #45494D;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    color: #EA2F4E;\n"
"}")
        self.CloseWindowButton.setObjectName("CloseWindowButton")
        self.MinimizeWindowButton = QtWidgets.QPushButton(self.WindowFrame)
        self.MinimizeWindowButton.setGeometry(QtCore.QRect(660, 0, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.MinimizeWindowButton.setFont(font)
        self.MinimizeWindowButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.MinimizeWindowButton.setStyleSheet("QPushButton{\n"
"    color: white;\n"
"    border: none;\n"
"    border-top-right-radius: 7px;\n"
"    background-color: #2C313C;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #45494D;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    color: #EA2F4E;\n"
"}")
        self.MinimizeWindowButton.setDefault(False)
        self.MinimizeWindowButton.setObjectName("MinimizeWindowButton")
        self.SaveBotSettingsButton = QtWidgets.QPushButton(self.WindowFrame)
        self.SaveBotSettingsButton.setGeometry(QtCore.QRect(629, 0, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.SaveBotSettingsButton.setFont(font)
        self.SaveBotSettingsButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.SaveBotSettingsButton.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"    border-top-right-radius: 7px;\n"
"    background-color: #2C313C;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #45494D;\n"
"}")
        self.SaveBotSettingsButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Icons/SaveOff.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.SaveBotSettingsButton.setIcon(icon)
        self.SaveBotSettingsButton.setIconSize(QtCore.QSize(25, 25))
        self.SaveBotSettingsButton.setObjectName("SaveBotSettingsButton")
        self.VKTokenLineEdit = QtWidgets.QLineEdit(self.Window)
        self.VKTokenLineEdit.setGeometry(QtCore.QRect(20, 50, 331, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.VKTokenLineEdit.setFont(font)
        self.VKTokenLineEdit.setStyleSheet("QLineEdit{\n"
"    border-bottom-left-radius: 12px;\n"
"    border-top-left-radius: 12px;\n"
"}")
        self.VKTokenLineEdit.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText|QtCore.Qt.ImhSensitiveData)
        self.VKTokenLineEdit.setInputMask("")
        self.VKTokenLineEdit.setText("")
        self.VKTokenLineEdit.setFrame(False)
        self.VKTokenLineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.VKTokenLineEdit.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.VKTokenLineEdit.setObjectName("VKTokenLineEdit")
        self.IDBotLineEdit = QtWidgets.QLineEdit(self.Window)
        self.IDBotLineEdit.setGeometry(QtCore.QRect(20, 100, 371, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.IDBotLineEdit.setFont(font)
        self.IDBotLineEdit.setStyleSheet("QLineEdit{\n"
"    border-radius: 12px;\n"
"}")
        self.IDBotLineEdit.setInputMask("")
        self.IDBotLineEdit.setText("")
        self.IDBotLineEdit.setFrame(False)
        self.IDBotLineEdit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.IDBotLineEdit.setDragEnabled(False)
        self.IDBotLineEdit.setReadOnly(False)
        self.IDBotLineEdit.setObjectName("IDBotLineEdit")
        self.frame = QtWidgets.QFrame(self.Window)
        self.frame.setGeometry(QtCore.QRect(350, 50, 41, 41))
        self.frame.setStyleSheet("QFrame{\n"
"    border-bottom-right-radius: 12px;\n"
"    border-top-right-radius: 12px;\n"
"    border-bottom-left-radius: 0px;\n"
"    border-top-left-radius: 0px;\n"
"    background-color: white;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.ShowVKTokenButton = QtWidgets.QPushButton(self.frame)
        self.ShowVKTokenButton.setGeometry(QtCore.QRect(0, 0, 41, 41))
        self.ShowVKTokenButton.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"}")
        self.ShowVKTokenButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../Icons/eyeOn.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ShowVKTokenButton.setIcon(icon1)
        self.ShowVKTokenButton.setIconSize(QtCore.QSize(32, 32))
        self.ShowVKTokenButton.setObjectName("ShowVKTokenButton")
        self.label = QtWidgets.QLabel(self.Window)
        self.label.setGeometry(QtCore.QRect(400, 50, 301, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel{\n"
"    color: white;\n"
"}")
        self.label.setObjectName("label")
        self.AutomatiAuthorizatonButton = QtWidgets.QPushButton(self.Window)
        self.AutomatiAuthorizatonButton.setGeometry(QtCore.QRect(702, 52, 20, 21))
        self.AutomatiAuthorizatonButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.AutomatiAuthorizatonButton.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"}")
        self.AutomatiAuthorizatonButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../Icons/Off.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.AutomatiAuthorizatonButton.setIcon(icon2)
        self.AutomatiAuthorizatonButton.setIconSize(QtCore.QSize(16, 16))
        self.AutomatiAuthorizatonButton.setObjectName("AutomatiAuthorizatonButton")
        self.label_2 = QtWidgets.QLabel(self.Window)
        self.label_2.setGeometry(QtCore.QRect(400, 70, 291, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel{\n"
"    color: white;\n"
"}")
        self.label_2.setObjectName("label_2")
        self.UserCommandsButton = QtWidgets.QPushButton(self.Window)
        self.UserCommandsButton.setGeometry(QtCore.QRect(685, 73, 20, 21))
        self.UserCommandsButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.UserCommandsButton.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"}")
        self.UserCommandsButton.setText("")
        self.UserCommandsButton.setIcon(icon2)
        self.UserCommandsButton.setIconSize(QtCore.QSize(16, 16))
        self.UserCommandsButton.setObjectName("UserCommandsButton")
        self.AddUserCommandButton = QtWidgets.QPushButton(self.Window)
        self.AddUserCommandButton.setGeometry(QtCore.QRect(400, 100, 321, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.AddUserCommandButton.setFont(font)
        self.AddUserCommandButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.AddUserCommandButton.setStyleSheet("QPushButton{\n"
"    color: white;\n"
"    border-radius: 8px;\n"
"    background-color: #595F76;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #50566E;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: #434965;\n"
"}")
        self.AddUserCommandButton.setObjectName("AddUserCommandButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.CloseWindowButton.setText(_translate("Form", "X"))
        self.MinimizeWindowButton.setText(_translate("Form", "_"))
        self.VKTokenLineEdit.setPlaceholderText(_translate("Form", "Введите VK Token бота"))
        self.IDBotLineEdit.setPlaceholderText(_translate("Form", "Введите ID бота"))
        self.label.setText(_translate("Form", "Автоматическая авторизация:"))
        self.label_2.setText(_translate("Form", "Пользовательские команды:"))
        self.AddUserCommandButton.setText(_translate("Form", "Добавить команду"))
